TARGET_CLASSES = {

0:"bad apple",
1:"bad banana",
2: "bad beans",
3: "bad brinjal",
4:"bad broccoli",
5: "bad cabbage",
6:"bad capsicum",
7: "bad carrot",
8:"bad cauliflower",
9:"bad chilli",
10:"bad coriander",
11:"bad corn",
12:"bad cucumber",
13:"bad garlic",
14:"bad ginger",
15:"bad gooseberry",
16:"bad grapes",
17:"bad lemon",
18:"bad mango",
19:"bad mushroom",
20:"bad onion",
21:"bad orange",
22:"bad papaya",
23:"bad peach",
24:"bad pear",
25:"bad plum",
26:"bad potato",
27:"bad raddish",
28:"bad spinach",
29:"bad strawberry",
30:"bad tomato",
31:"good apple",
32:"good banana",
33:"good beans",
34:"good brinjal",
35:"good broccoli",
36:"good cabbage",
39:"good capsicum",
40:"good carrot",
41:"good cauliflower",
42:"good chilli",
43:"good coriander",
44:"good corn",
45:"good cucumber",
46:"good garlic",
47:"good ginger",
48:"good gooseberry",
49:"good grapes",
50:"good lemon",
51:"good mango",
52:"good mushroom",
53:"good onion",
54:"good orange",
55:"good papaya",
56:"good peach",
57:"good pear",
58:"good plum",
59:"good potato",
60:"good raddish",
61:"good spinach",
62:"good strawberry",
63:"good tomato"
};
